# Generated by Django 5.2.3 on 2025-07-14 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_objectives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoSectorial',
            fields=[
                ('objetivo_sectorial_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('plan_sectorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='strategic_objectives.plansectorial')),
            ],
        ),
    ]
