# Generated by Django 5.2.4 on 2025-12-09 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_objectives', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objetivodesarrollosostenible',
            name='icono',
        ),
    ]
