# Generated by Django 5.2.3 on 2025-07-05 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_objectives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planinstitucional',
            name='version_actual',
            field=models.PositiveIntegerField(default=1, help_text='La versión actual del plan'),
        ),
        migrations.CreateModel(
            name='PlanInstitucionalVersion',
            fields=[
                ('version_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_version', models.PositiveIntegerField()),
                ('fecha_version', models.DateTimeField(auto_now_add=True)),
                ('datos', models.JSONField(help_text='Snapshot de los datos del plan en esta versión')),
                ('plan_institucional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='strategic_objectives.planinstitucional')),
                ('usuario_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_version'],
            },
        ),
    ]
