# Generated by Django 5.2.3 on 2025-07-07 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional_config', '0001_initial'),
        ('strategic_objectives', '0002_planinstitucional_version_actual_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaInstitucional',
            fields=[
                ('programa_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('version_actual', models.PositiveIntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas', to='institutional_config.entidad')),
                ('oei_alineados', models.ManyToManyField(blank=True, related_name='programas_alineados', to='strategic_objectives.objetivoestrategicoinstitucional')),
            ],
            options={
                'verbose_name': 'Programa Institucional',
                'verbose_name_plural': 'Programas Institucionales',
            },
        ),
    ]
