# Generated by Django 5.2.4 on 2025-12-10 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional_config', '0001_initial'),
        ('strategic_objectives', '0002_remove_objetivodesarrollosostenible_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannacionaldesarrollo',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='institutional_config.periodoplanificacion'),
        ),
    ]
