# Generated by Django 5.2.3 on 2025-07-15 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_objectives', '0002_objetivosectorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planinstitucional',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
