# Generated by Django 5.2.3 on 2025-07-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_objectives', '0003_planinstitucional_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='alineacion',
            name='ods_vinculados',
            field=models.ManyToManyField(blank=True, related_name='alineaciones', to='strategic_objectives.objetivodesarrollosostenible'),
        ),
    ]
