# Generated by Django 5.2.3 on 2025-07-08 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre del catálogo (ej. 'Sectores', 'Tipos de Plan')", max_length=255, unique=True)),
                ('codigo', models.CharField(help_text='Código único para el catálogo', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Catálogo',
                'verbose_name_plural': 'Catálogos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoPlanificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej: 'Planificación Estratégica 2025-2029'", max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('EN_CIERRE', 'En Cierre')], default='ABIERTO', max_length=20)),
                ('es_activo_para_carga', models.BooleanField(default=False, help_text='Indica si en este período se puede ingresar nueva información.')),
            ],
            options={
                'verbose_name': 'Período de Planificación',
                'verbose_name_plural': 'Períodos de Planificación',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ItemCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre del item (ej. 'Salud', 'Educación')", max_length=255)),
                ('codigo', models.CharField(blank=True, help_text='Código opcional para el item', max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='institutional_config.catalogo')),
            ],
            options={
                'verbose_name': 'Ítem de Catálogo',
                'verbose_name_plural': 'Ítems de Catálogos',
                'ordering': ['catalogo__nombre', 'nombre'],
                'unique_together': {('catalogo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('codigo_unico', models.CharField(help_text='Código único de creación de la entidad', max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nivel_gobierno', models.ForeignKey(help_text='Nivel de gobierno al que pertenece la entidad', limit_choices_to={'catalogo__codigo': 'NIVEL_GOBIERNO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entidades_por_nivel', to='institutional_config.itemcatalogo')),
                ('sector', models.ForeignKey(blank=True, limit_choices_to={'catalogo__codigo': 'SECTORES'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entidades_por_sector', to='institutional_config.itemcatalogo')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadOrganizacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='institutional_config.entidad')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='institutional_config.unidadorganizacional')),
            ],
            options={
                'verbose_name': 'Unidad Organizacional',
                'verbose_name_plural': 'Unidades Organizacionales',
                'ordering': ['entidad__nombre', 'nombre'],
                'unique_together': {('entidad', 'nombre')},
            },
        ),
    ]
