# Generated by Django 5.2.4 on 2025-09-05 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional_config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidad',
            name='sector',
        ),
        migrations.AddField(
            model_name='entidad',
            name='subsector',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalogo__codigo': 'SUBSECTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entidades_por_subsector', to='institutional_config.itemcatalogo'),
        ),
    ]
