# Generated by Django 5.2.4 on 2025-09-05 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional_config', '0002_remove_entidad_sector_entidad_subsector'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadorganizacional',
            name='macrosector',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalogo__codigo': 'MACROSECTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_por_macrosector', to='institutional_config.itemcatalogo'),
        ),
        migrations.AddField(
            model_name='unidadorganizacional',
            name='sectores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'catalogo__codigo': 'SECTOR'}, related_name='unidades_por_sector', to='institutional_config.itemcatalogo'),
        ),
    ]
