# Generated by Django 5.2.4 on 2025-09-05 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional_config', '0003_unidadorganizacional_macrosector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcatalogo',
            name='padre',
            field=models.ForeignKey(blank=True, help_text='Ítem padre para crear jerarquías (ej. un Sector bajo un MacroSector).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='institutional_config.itemcatalogo'),
        ),
    ]
