# Generated by Django 5.2.4 on 2025-09-05 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional_config', '0004_itemcatalogo_padre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadorganizacional',
            name='macrosector',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalogo__codigo': 'CLASIFICADOR_SECTORIAL', 'padre__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_por_macrosector', to='institutional_config.itemcatalogo'),
        ),
        migrations.AlterField(
            model_name='unidadorganizacional',
            name='sectores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'catalogo__codigo': 'CLASIFICADOR_SECTORIAL'}, related_name='unidades_por_sector', to='institutional_config.itemcatalogo'),
        ),
    ]
