# Generated by Django 5.2.3 on 2025-07-08 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutional_config', '0001_initial'),
        ('investment_projects', '0001_initial'),
        ('strategic_objectives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectoinversion',
            name='programa_institucional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='strategic_objectives.programainstitucional'),
        ),
        migrations.AddField(
            model_name='proyectoinversion',
            name='sector',
            field=models.ForeignKey(limit_choices_to={'catalogo__codigo': 'SECTORES'}, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_por_sector', to='institutional_config.itemcatalogo'),
        ),
        migrations.AddField(
            model_name='proyectoinversion',
            name='tipo_proyecto',
            field=models.ForeignKey(limit_choices_to={'catalogo__codigo': 'TIPO_PROYECTO'}, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_por_tipo', to='institutional_config.itemcatalogo'),
        ),
        migrations.AddField(
            model_name='proyectoinversion',
            name='tipologia_proyecto',
            field=models.ForeignKey(limit_choices_to={'catalogo__codigo': 'TIPOLOGIA_PROYECTO'}, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_por_tipologia', to='institutional_config.itemcatalogo'),
        ),
        migrations.AddField(
            model_name='marcologico',
            name='proyecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marco_logico', to='investment_projects.proyectoinversion'),
        ),
        migrations.AddField(
            model_name='dictamenprioridad',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictamenes', to='investment_projects.proyectoinversion'),
        ),
        migrations.AddField(
            model_name='arrastreinversion',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrastres', to='investment_projects.proyectoinversion'),
        ),
        migrations.AddField(
            model_name='proyectoinversionversion',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='investment_projects.proyectoinversion'),
        ),
        migrations.AddField(
            model_name='proyectoinversionversion',
            name='usuario_responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
