# Generated by Django 5.2.3 on 2025-07-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectoinversion',
            name='contribucion_programa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de contribución del proyecto al Programa Institucional vinculado.', max_digits=5, null=True),
        ),
    ]
