# Generated by Django 5.2.4 on 2025-12-11 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional_config', '0001_initial'),
        ('investment_projects', '0003_alter_proyectoinversion_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectoinversion',
            name='sector',
            field=models.ForeignKey(limit_choices_to={'catalogo__codigo': 'SECTORES'}, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_por_sector', to='institutional_config.itemcatalogo'),
        ),
    ]
