# Generated by Django 5.2.4 on 2025-08-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_projects', '0003_proyectoinversion_contribucion_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectoinversion',
            name='ultimas_observaciones',
            field=models.TextField(blank=True, help_text='Observaciones de la última revisión del proyecto.', null=True),
        ),
    ]
