# Generated by Django 5.2.4 on 2025-09-05 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_projects', '0004_proyectoinversion_ultimas_observaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioPriorizacion',
            fields=[
                ('criterio_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('ponderacion', models.DecimalField(decimal_places=2, help_text='Peso del criterio en el puntaje total (ej. 30.00 para 30%)', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PuntuacionProyecto',
            fields=[
                ('puntuacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion_asignada', models.DecimalField(decimal_places=2, max_digits=5)),
                ('justificacion', models.TextField(blank=True, help_text='Justificación de la puntuación asignada.')),
                ('fecha_evaluacion', models.DateTimeField(auto_now=True)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones', to='investment_projects.criteriopriorizacion')),
                ('evaluador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntuaciones', to='investment_projects.proyectoinversion')),
            ],
            options={
                'unique_together': {('proyecto', 'criterio')},
            },
        ),
    ]
