# Generated by Django 5.2.4 on 2026-07-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_projects', '0005_alter_proyectoinversion_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectoinversion',
            name='estado',
            field=models.CharField(choices=[('EN_FORMULACION', 'En Formulación'), ('POSTULADO', 'Postulado'), ('PRIORIZADO', 'Priorizado')], default='EN_FORMULACION', max_length=50),
        ),
    ]
