# Generated by Django 5.2.4 on 2026-07-09 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditevent',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Evento de Auditoría', 'verbose_name_plural': 'Eventos de Auditoría'},
        ),
    ]
