# Generated by Django 5.2.4 on 2026-07-19 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditevent_options'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='request_method',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Método HTTP'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='request_path',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ruta'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='success',
            field=models.BooleanField(default=True, verbose_name='Éxito'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='User-Agent'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
