# Generated by Django 5.2.4 on 2026-01-27 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investment_projects', '0005_alter_proyectoinversion_sector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rule', models.CharField(choices=[('AND', 'Todos los indicadores deben estar cumplidos'), ('OR', 'Al menos un indicador debe estar cumplido')], default='AND', max_length=3)),
                ('status', models.CharField(choices=[('NO_INICIADO', 'No Iniciado'), ('EN_PROGRESO', 'En Progreso'), ('CUMPLIDO', 'Cumplido'), ('NO_CUMPLIDO', 'No Cumplido')], default='NO_INICIADO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('real_start_date', models.DateField(blank=True, null=True)),
                ('real_end_date', models.DateField(blank=True, null=True)),
                ('planned_progress', models.FloatField(default=100)),
                ('real_progress', models.FloatField(default=0)),
                ('reported_status', models.CharField(choices=[('NO_INICIADA', 'No Iniciada'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada'), ('EN_RIESGO', 'En Riesgo')], default='NO_INICIADA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tracking_activities', to=settings.AUTH_USER_MODEL)),
                ('objectives', models.ManyToManyField(related_name='tracking_activities', to='tracking.objective')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_activities', to='investment_projects.proyectoinversion')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tracking_activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(default='tracking', max_length=50)),
                ('action', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tracking.trackingactivity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
