# Generated by Django 5.2.4 on 2026-01-27 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_projects', '0005_alter_proyectoinversion_sector'),
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingactivity',
            name='activity_code',
            field=models.CharField(blank=True, editable=False, help_text='Código de actividad único por proyecto', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trackingactivity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingactivity',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si la actividad está activa (para borrado lógico)'),
        ),
        migrations.AddField(
            model_name='trackingactivity',
            name='planned_duration_days',
            field=models.IntegerField(blank=True, editable=False, help_text='Duración planificada en días', null=True),
        ),
        migrations.AddField(
            model_name='trackingactivity',
            name='priority',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
        migrations.AddField(
            model_name='trackingactivity',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trackingactivity',
            name='reported_status',
            field=models.CharField(choices=[('PLANIFICADA', 'Planificada'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada'), ('EN_RIESGO', 'En Riesgo')], default='PLANIFICADA', max_length=20),
        ),
        migrations.RemoveField(
            model_name='trackingactivity',
            name='planned_progress',
        ),
        migrations.RemoveField(
            model_name='trackingactivity',
            name='real_progress',
        ),
        migrations.AlterUniqueTogether(
            name='trackingactivity',
            unique_together={('project', 'activity_code')},
        ),
    ]
