# Generated by Django 5.2.4 on 2026-01-27 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategic_objectives', '0004_alter_plansectorial_periodo'),
        ('tracking', '0002_alter_trackingactivity_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='strategic_objective',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_objectives', to='strategic_objectives.objetivoestrategicoinstitucional'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='name',
            field=models.CharField(help_text='Nombre específico para el objetivo de seguimiento', max_length=255),
        ),
        migrations.AlterField(
            model_name='objective',
            name='rule',
            field=models.CharField(choices=[('AND', 'Todos'), ('OR', 'Al menos uno')], default='AND', max_length=3),
        ),
        migrations.AlterField(
            model_name='trackingactivity',
            name='activity_code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trackingactivity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trackingactivity',
            name='planned_duration_days',
            field=models.IntegerField(editable=False),
        ),
        migrations.DeleteModel(
            name='TrackingHistory',
        ),
    ]
