# Generated by Django 5.2.4 on 2026-07-19 01:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_objective_strategic_objective_alter_objective_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingactivity',
            name='real_progress',
            field=models.IntegerField(default=0, help_text='Porcentaje de avance real reportado (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
