# Generated by Django 5.2.4 on 2026-07-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_trackingactivity_real_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingactivity',
            name='activity_code',
            field=models.CharField(blank=True, default='', editable=False, max_length=20),
        ),
    ]
