# Generated by Django 5.2.4 on 2025-09-05 03:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre_usuario', models.CharField(max_length=150, unique=True)),
                ('entidad_codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('datos_basicos', models.JSONField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('esta_bloqueado', models.BooleanField(default=False)),
                ('fecha_bloqueo', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('roles', models.ManyToManyField(blank=True, related_name='usuarios', to='authentication.rol')),
            ],
            options={
                'db_table': 'authentication_usuario',
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('registro_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('modulo', models.CharField(default='Planificacion', max_length=100)),
                ('funcionalidad', models.CharField(default='General', max_length=100)),
                ('accion', models.CharField(default='Desconocido', max_length=100)),
                ('entidad_afectada_tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('entidad_afectada_id', models.IntegerField(blank=True, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registro_auditoria',
            },
        ),
    ]
