# Generated by Django 5.2.3 on 2025-06-24 19:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuarios_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_usuario', models.CharField(max_length=150, unique=True)),
                ('entidad_codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('roles', models.TextField()),
                ('datos_basicos', models.JSONField()),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('registro_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('modulo', models.CharField(default='Planificacion', max_length=100)),
                ('funcionalidad', models.CharField(blank=True, max_length=100, null=True)),
                ('accion', models.CharField(blank=True, max_length=100, null=True)),
                ('entidad_afectada_tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('entidad_afectada_id', models.IntegerField(blank=True, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.usuario')),
            ],
        ),
    ]
