# Generated by Django 5.2.4 on 2025-12-09 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rol_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='fecha_creacion',
        ),
    ]
