# Generated by Django 5.2.3 on 2025-06-24 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_usuario_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='esta_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='authentication_usuario',
        ),
    ]
