# Generated by Django 5.2.4 on 2025-12-09 23:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_rol_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
