# Generated by Django 5.2.3 on 2025-06-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_usuario_esta_activo_alter_usuario_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='accion',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='funcionalidad',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='registroauditoria',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name='registroauditoria',
            table='registro_auditoria',
        ),
    ]
