# Generated by Django 5.2.3 on 2025-06-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_registroauditoria_accion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuarios_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
